######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 3 15:33:59 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += servicemanager.h
SOURCES += main.cpp servicemanager.cpp service.cpp client.cpp
