######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 10 16:54:22 2009
######################################################################

TEMPLATE = app
TARGET = runtest
DEPENDPATH += .
INCLUDEPATH += .
QT += network testlib

# Input
HEADERS += servicemanager.h test.h
SOURCES += client.cpp service.cpp servicemanager.cpp test.cpp
