######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 10 16:54:22 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network 

# Input
HEADERS += servicemanager.h
SOURCES += client.cpp main.cpp service.cpp servicemanager.cpp
