linkedlist: LinkedList.h CircularList.h DoubleLinkedList.h main.cpp
	g++ -o linkedlist main.cpp  
	./linkedlist
clean: 
	rm linkedlist
debug: LinkedList.h CircularList.h DoubleLinkedList.h main.cpp
	g++ -o linkedlist main.cpp -g
	gdb linkedlist
