######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 10 17:02:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += thread.h
SOURCES += main.cpp
